<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->string('id', 8)->primary();
        });
        DB::table('countries')->insert([
            ['id' => 'af'],
            ['id' => 'ax'],
            ['id' => 'al'],
            ['id' => 'dz'],
            ['id' => 'as'],
            ['id' => 'ad'],
            ['id' => 'ao'],
            ['id' => 'ai'],
            ['id' => 'aq'],
            ['id' => 'ag'],
            ['id' => 'ar'],
            ['id' => 'am'],
            ['id' => 'aw'],
            ['id' => 'au'],
            ['id' => 'at'],
            ['id' => 'az'],
            ['id' => 'bs'],
            ['id' => 'bh'],
            ['id' => 'bd'],
            ['id' => 'bb'],
            ['id' => 'by'],
            ['id' => 'be'],
            ['id' => 'bz'],
            ['id' => 'bj'],
            ['id' => 'bm'],
            ['id' => 'bt'],
            ['id' => 'bo'],
            ['id' => 'bq'],
            ['id' => 'ba'],
            ['id' => 'bw'],
            ['id' => 'bv'],
            ['id' => 'br'],
            ['id' => 'io'],
            ['id' => 'vg'],
            ['id' => 'bn'],
            ['id' => 'bg'],
            ['id' => 'bf'],
            ['id' => 'bi'],
            ['id' => 'kh'],
            ['id' => 'cm'],
            ['id' => 'ca'],
            ['id' => 'cv'],
            ['id' => 'ky'],
            ['id' => 'cf'],
            ['id' => 'td'],
            ['id' => 'cl'],
            ['id' => 'cn'],
            ['id' => 'cx'],
            ['id' => 'cc'],
            ['id' => 'co'],
            ['id' => 'km'],
            ['id' => 'ck'],
            ['id' => 'cr'],
            ['id' => 'hr'],
            ['id' => 'cu'],
            ['id' => 'cw'],
            ['id' => 'cy'],
            ['id' => 'cz'],
            ['id' => 'cd'],
            ['id' => 'dk'],
            ['id' => 'dj'],
            ['id' => 'dm'],
            ['id' => 'do'],
            ['id' => 'tl'],
            ['id' => 'ec'],
            ['id' => 'eg'],
            ['id' => 'sv'],
            ['id' => 'gq'],
            ['id' => 'er'],
            ['id' => 'ee'],
            ['id' => 'et'],
            ['id' => 'fk'],
            ['id' => 'fo'],
            ['id' => 'fj'],
            ['id' => 'fi'],
            ['id' => 'fr'],
            ['id' => 'gf'],
            ['id' => 'pf'],
            ['id' => 'tf'],
            ['id' => 'ga'],
            ['id' => 'gm'],
            ['id' => 'ge'],
            ['id' => 'de'],
            ['id' => 'gh'],
            ['id' => 'gi'],
            ['id' => 'gr'],
            ['id' => 'gl'],
            ['id' => 'gd'],
            ['id' => 'gp'],
            ['id' => 'gu'],
            ['id' => 'gt'],
            ['id' => 'gg'],
            ['id' => 'gn'],
            ['id' => 'gw'],
            ['id' => 'gy'],
            ['id' => 'ht'],
            ['id' => 'hm'],
            ['id' => 'hn'],
            ['id' => 'hk'],
            ['id' => 'hu'],
            ['id' => 'is'],
            ['id' => 'in'],
            ['id' => 'id'],
            ['id' => 'ir'],
            ['id' => 'iq'],
            ['id' => 'ie'],
            ['id' => 'im'],
            ['id' => 'il'],
            ['id' => 'it'],
            ['id' => 'ci'],
            ['id' => 'jm'],
            ['id' => 'jp'],
            ['id' => 'je'],
            ['id' => 'jo'],
            ['id' => 'kz'],
            ['id' => 'ke'],
            ['id' => 'ki'],
            ['id' => 'xk'],
            ['id' => 'kw'],
            ['id' => 'kg'],
            ['id' => 'la'],
            ['id' => 'lv'],
            ['id' => 'lb'],
            ['id' => 'ls'],
            ['id' => 'lr'],
            ['id' => 'ly'],
            ['id' => 'li'],
            ['id' => 'lt'],
            ['id' => 'lu'],
            ['id' => 'mo'],
            ['id' => 'mk'],
            ['id' => 'mg'],
            ['id' => 'mw'],
            ['id' => 'my'],
            ['id' => 'mv'],
            ['id' => 'ml'],
            ['id' => 'mt'],
            ['id' => 'mh'],
            ['id' => 'mq'],
            ['id' => 'mr'],
            ['id' => 'mu'],
            ['id' => 'yt'],
            ['id' => 'mx'],
            ['id' => 'fm'],
            ['id' => 'md'],
            ['id' => 'mc'],
            ['id' => 'mn'],
            ['id' => 'me'],
            ['id' => 'ms'],
            ['id' => 'ma'],
            ['id' => 'mz'],
            ['id' => 'mm'],
            ['id' => 'na'],
            ['id' => 'nr'],
            ['id' => 'np'],
            ['id' => 'nl'],
            ['id' => 'nc'],
            ['id' => 'nz'],
            ['id' => 'ni'],
            ['id' => 'ne'],
            ['id' => 'ng'],
            ['id' => 'nu'],
            ['id' => 'nf'],
            ['id' => 'kp'],
            ['id' => 'mp'],
            ['id' => 'no'],
            ['id' => 'om'],
            ['id' => 'pk'],
            ['id' => 'pw'],
            ['id' => 'ps'],
            ['id' => 'pa'],
            ['id' => 'pg'],
            ['id' => 'py'],
            ['id' => 'pe'],
            ['id' => 'ph'],
            ['id' => 'pn'],
            ['id' => 'pl'],
            ['id' => 'pt'],
            ['id' => 'pr'],
            ['id' => 'qa'],
            ['id' => 'cg'],
            ['id' => 're'],
            ['id' => 'ro'],
            ['id' => 'ru'],
            ['id' => 'rw'],
            ['id' => 'bl'],
            ['id' => 'sh'],
            ['id' => 'kn'],
            ['id' => 'lc'],
            ['id' => 'mf'],
            ['id' => 'pm'],
            ['id' => 'vc'],
            ['id' => 'ws'],
            ['id' => 'sm'],
            ['id' => 'st'],
            ['id' => 'sa'],
            ['id' => 'sn'],
            ['id' => 'rs'],
            ['id' => 'sc'],
            ['id' => 'sl'],
            ['id' => 'sg'],
            ['id' => 'sx'],
            ['id' => 'sk'],
            ['id' => 'si'],
            ['id' => 'sb'],
            ['id' => 'so'],
            ['id' => 'za'],
            ['id' => 'gs'],
            ['id' => 'kr'],
            ['id' => 'ss'],
            ['id' => 'es'],
            ['id' => 'lk'],
            ['id' => 'sd'],
            ['id' => 'sr'],
            ['id' => 'sj'],
            ['id' => 'sz'],
            ['id' => 'se'],
            ['id' => 'ch'],
            ['id' => 'sy'],
            ['id' => 'tw'],
            ['id' => 'tj'],
            ['id' => 'tz'],
            ['id' => 'th'],
            ['id' => 'tg'],
            ['id' => 'tk'],
            ['id' => 'to'],
            ['id' => 'tt'],
            ['id' => 'tn'],
            ['id' => 'tr'],
            ['id' => 'tm'],
            ['id' => 'tc'],
            ['id' => 'tv'],
            ['id' => 'vi'],
            ['id' => 'ug'],
            ['id' => 'ua'],
            ['id' => 'ae'],
            ['id' => 'gb'],
            ['id' => 'us'],
            ['id' => 'um'],
            ['id' => 'uy'],
            ['id' => 'uz'],
            ['id' => 'vu'],
            ['id' => 'va'],
            ['id' => 've'],
            ['id' => 'vn'],
            ['id' => 'wf'],
            ['id' => 'eh'],
            ['id' => 'ye'],
            ['id' => 'zm'],
            ['id' => 'zw'],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
